### ISSUE TITLE
Support for pic32

### ISSUE THREAD

**Issue by realblades** [WallaceIT/picberry#1]
I would like to see support for pic32 chips especially since they aren't supported by pickit2 or any other Free tools I've found.

**Comment by WallaceIT** [comment]
A quick update, nearly two years later.
I added preliminary support for PIC32 devices, I can now write and read device memory.
Unfortunately, my basic blinky firmware seems not to start, and currently I do not have enough time nor an alternative programmer (such as a PicKit3) to check what's wrong.

**Comment by WallaceIT** [comment]
Tested today after another 6-months and a basic blink firmware runs successfully on PIC32MX250F128B.
Basic pic32mx (and theoretically mz) support can be considered as added, but needs testing.
