### ISSUE TITLE
Regarding programming PIC from raspberry pi using picberry software tool

### ISSUE THREAD

**Issue by rkabade** [WallaceIT/picberry#15]
I found the Device Libraries(.h and .cpp) which supports "PIC24FJ256GB206" in Available PIC Families "pic24fjxxxga3xx" 
I had followed the installation steps of picberry using the link: https://github.com/WallaceIT/picberry
And I tried to flash the PIC board of controller "PIC24FJ256GB206" using below command and It is giving me ERROR.

root@raspberrypi:/home/pi/vendingserver/picberry# sudo picberry -w Elock2.54.X.test_release.hex
picberry PIC Programmer v0.2
Device ID: 0xffff
ERROR: unknown/unsupported device or programmer not connected.
Press ENTER to exit program mode...

Could you please tell me where i am getting wrong or please let me know how to debug this issue?
If any one tried this with other PIC controller and got the result, Please guide me.

**Comment by rkabade** [comment]
Could we have list of supported PIC Device for picberry tool?
It may be good to first get it working with one of the supported devices.

Thanks
Rakesh

**Comment by rkabade** [comment]
I am able to flash the hex file. Thanks a lot !!!!
picberry PIC Programmer v0.2
Device Name: PIC24FJ256GB206
Device ID: 0x00004104
Revision: 0x00000004
Writing chip...[DONE! 
Press ENTER to exit program mode...

**Comment by WallaceIT** [comment]
Hello @rkabade,
picberry has only been tested with few real PIC microcontrollers, since it has been developed as an hobby project - while theoretically compatibility should be there for every listed part, no real test has been performed.
If you have the chance to test it with several different parts, feel free to compile a list and to add it to the README.

**Comment by rkabade** [comment]
Dear Francesco,
Yes I have tested the picberry in PIC24FJ256GB206 and Its working as
expected. I am able to flash PIC from RaspberryPi 3 Model B.
Its working awesome and helped us to achieve the project deadline.
Thanks a lot for you picberry hobby project that you have created.
Yes I will also add the tested parts in Readme.

Thanks
Rakesh K
+918861017354.

*Thanks,*
*Rakesh Kabade*
*Lead System Engineer*
