### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by gtsiros** [WallaceIT/picberry#2]
had to mkdir -p build/devices and change g++-4.7 to g++-4.9 in the makefile

even so, compilation fails at

> src/gpio_test.cpp:93:93: error: expression cannot be used as a function
>      cout << "BASE ADDRESS " << hex << GPIO_BASE << " + OFFSET " << hex << **OFFSET(tested_gpio)** << " = FINAL ADDRESS " << hex << GPIO_BASE + **OFFSET(tested_gpio)** << endl;

(bold for emphasis mine)

**Comment by WallaceIT** [comment]
Compilation fixed in commit 8f0c7c3, except for g++ version (I'll work on that tomorrow).
Please test and report in case of issues.
Thanks!

**Comment by WallaceIT** [comment]
Is commit 3119907, actually...

**Comment by gtsiros** [comment]
It compiled now, awesome. :D

If i knew more about this, i would do a throw myself. Or a pull. Push. Whatever it's called in git-land. :P

**Comment by WallaceIT** [comment]
I think the term you're searching for is "pull request" :)
